server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.mvc: DEBUG
    org.springframework.web: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
